services:
  base-image:
    image: home-server-remote/base-image
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app

  dev:
    container_name: home-server-remote-dev
    image: home-server-remote/base-image
    ports:
      - 8000:8000
    environment:
      - FLASK_ENV=dev
      - GPIOZERO_PIN_FACTORY=mock
    volumes:
      - ./:/app
    command: gunicorn -c /app/config/gunicorn/dev.py service.app:flask_app
    restart: unless-stopped

  test:
    image: home-server-remote/base-image
    container_name: test
    environment:
      - FLASK_ENV=test
    volumes:
      - ./:/app

  prod:
    container_name: home-server-remote-prod
    image: home-server-remote/base-image
    ports:
      - 80:5656
    environment:
      - FLASK_ENV=prod
      - GPIOZERO_PIN_FACTORY=native
    volumes:
      - ./:/app
    command: gunicorn -c /app/config/gunicorn/production.py service.app:flask_app
    restart: unless-stopped
