[tool.mypy]
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.coverage.run]
data_file = "./tmp/.coverage"

[tool.coverage.report]
fail_under = 100

[tool.pytest.ini_options]
addopts = "--cov=service --durations=10"
